swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8081'
basePath: /
tags:
  - name: auth-controller
    description: Auth Controller
  - name: email-admin-controller
    description: Email Admin Controller
paths:
  /api/v1/nosy/auth/logout:
    get:
      tags:
        - auth-controller
      summary: logout
      operationId: logoutUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/v1/nosy/auth/status:
    post:
      tags:
        - auth-controller
      summary: isAuthenticated
      operationId: isAuthenticatedUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: token
          description: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: boolean
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/v1/nosy/auth/token:
    post:
      tags:
        - auth-controller
      summary: getToken
      operationId: getTokenUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: userdto
          description: userdto
          required: true
          schema:
            $ref: '#/definitions/UserDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ClientToken'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/v1/nosy/inputsystems:
    get:
      tags:
        - email-admin-controller
      summary: getInputSystems
      operationId: getInputSystemsUsingGET
      produces:
        - '*/*'
      parameters:
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/InputSystemDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - email-admin-controller
      summary: newType
      operationId: newTypeUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: inputSystemDto
          description: inputSystemDto
          required: true
          schema:
            $ref: '#/definitions/InputSystemDto'
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/InputSystemDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/v1/nosy/inputsystems/emailproviders:
    get:
      tags:
        - email-admin-controller
      summary: getEmailAllProviders
      operationId: getEmailAllProvidersUsingGET
      produces:
        - '*/*'
      parameters:
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/api/v1/nosy/inputsystems/{inputSystemId}':
    put:
      tags:
        - email-admin-controller
      summary: updateInputSystemName
      operationId: updateInputSystemNameUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: inputSystemDto
          description: inputSystemDto
          required: true
          schema:
            $ref: '#/definitions/InputSystemDto'
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/InputSystemDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - email-admin-controller
      summary: deleteInputSystem
      operationId: deleteInputSystemUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/api/v1/nosy/inputsystems/{inputSystemId}/emailtemplates':
    get:
      tags:
        - email-admin-controller
      summary: getEmailTemplates
      operationId: getEmailTemplatesUsingGET
      produces:
        - '*/*'
      parameters:
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EmailTemplateDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - email-admin-controller
      summary: newEmailTemplate
      operationId: newEmailTemplateUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: emailTemplateDto
          description: emailTemplateDto
          required: true
          schema:
            $ref: '#/definitions/EmailTemplateDto'
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmailTemplateDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/api/v1/nosy/inputsystems/{inputSystemId}/emailtemplates/{emailTemplateId}':
    get:
      tags:
        - email-admin-controller
      summary: getEmailTemplateByInputSystemAndEmailTemplateId
      operationId: getEmailTemplateByInputSystemAndEmailTemplateIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: emailTemplateId
          in: path
          description: emailTemplateId
          required: true
          type: string
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmailTemplate'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - email-admin-controller
      summary: updateEmailTemplate
      operationId: updateEmailTemplateUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: emailTemplateDto
          description: emailTemplateDto
          required: true
          schema:
            $ref: '#/definitions/EmailTemplateDto'
        - name: emailTemplateId
          in: path
          description: emailTemplateId
          required: true
          type: string
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmailTemplateDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - email-admin-controller
      summary: deleteEmailTemplate
      operationId: deleteEmailTemplateUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: emailTemplateId
          in: path
          description: emailTemplateId
          required: true
          type: string
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/api/v1/nosy/inputsystems/{inputSystemId}/emailtemplates/{emailTemplateId}/post':
    post:
      tags:
        - email-admin-controller
      summary: emailTemplatePost
      operationId: emailTemplatePostUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: emailProviderProperties
          description: emailProviderProperties
          required: true
          schema:
            $ref: '#/definitions/EmailProviderProperties'
        - name: emailTemplateId
          in: path
          description: emailTemplateId
          required: true
          type: string
        - name: inputSystemId
          in: path
          description: inputSystemId
          required: true
          type: string
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmailTemplateDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/v1/nosy/users:
    get:
      tags:
        - auth-controller
      summary: getUserProfile
      operationId: getUserProfileUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - auth-controller
      summary: newUser
      operationId: newUserUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: userdto
          description: userdto
          required: true
          schema:
            $ref: '#/definitions/UserDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - auth-controller
      summary: deleteUsername
      operationId: deleteUsernameUsingDELETE
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false

definitions:
  ClientToken:
    type: object
    properties:
      accessToken:
        type: string
      expiresIn:
        type: integer
        format: int32
      refreshToken:
        type: string
    title: ClientToken
  EmailProviderProperties:
    type: object
    properties:
      password:
        type: string
      placeholders:
        type: array
        items:
          $ref: '#/definitions/PlaceHolder'
      username:
        type: string
    title: EmailProviderProperties
  EmailTemplate:
    type: object
    properties:
      emailTemplateCc:
        type: array
        items:
          type: string
      emailTemplateFromAddress:
        type: string
      emailTemplateFromProvider:
        type: string
        enum:
          - DEFAULT
          - YANDEX
          - GMAIL
      emailTemplateId:
        type: string
      emailTemplateName:
        type: string
      emailTemplatePriority:
        type: integer
        format: int32
      emailTemplateRetryPeriod:
        type: integer
        format: int32
      emailTemplateRetryTimes:
        type: integer
        format: int32
      emailTemplateSubject:
        type: string
      emailTemplateText:
        type: string
      emailTemplateTo:
        type: array
        items:
          type: string
      inputSystem:
        $ref: '#/definitions/InputSystem'
    title: EmailTemplate
  EmailTemplateDto:
    type: object
    properties:
      cc:
        type: array
        items:
          type: string
      fromAddress:
        type: string
      fromProvider:
        type: string
        enum:
          - DEFAULT
          - YANDEX
          - GMAIL
      id:
        type: string
      inputSystem:
        $ref: '#/definitions/InputSystem'
      name:
        type: string
      priority:
        type: integer
        format: int32
      retryPeriod:
        type: integer
        format: int32
      retryTimes:
        type: integer
        format: int32
      subject:
        type: string
      text:
        type: string
      to:
        type: array
        items:
          type: string
    title: EmailTemplateDto
  InputSystem:
    type: object
    properties:
      emailTemplate:
        type: array
        items:
          $ref: '#/definitions/EmailTemplate'
      inputSystemId:
        type: string
      inputSystemName:
        type: string
      user:
        $ref: '#/definitions/User'
    title: InputSystem
  InputSystemDto:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    title: InputSystemDto
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      view:
        $ref: '#/definitions/View'
      viewName:
        type: string
    title: ModelAndView
  PlaceHolder:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
    title: PlaceHolder
  User:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      info:
        type: string
      inputSystem:
        type: array
        items:
          $ref: '#/definitions/InputSystem'
      lastName:
        type: string
      password:
        type: string
    title: User
  UserDto:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      info:
        type: string
      lastName:
        type: string
      password:
        type: string
    title: UserDto
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View